id: P9E6EA794
initial_creation_type: input
source_metadata:
  title: Tāranātha Series
  language: bo
  description: 'Texts by and about Jetsün Tāranātha (rje btsun tA ra nA tha, 1575–1634),
    translator, prolific author and the second most important figure in the Jonang
    lineage:'
  volume:
    6647afd61bab4a3d89c832847d308e13:
      title: Brief Biography of Tāranātha
      parent: Biography
    91c735d0d66142b4aaa44eef02d0d006:
      title: 'Three Reasons for Confidence: A Work Telling the Life and Liberation
        Story of the Great Master Padmākara'
      parent: Biography
    6f30c78fe5bd418bb4c9466759028f26:
      title: 'Flower of Faith: In Praise of Tāranātha, Lord of Secrets'
      parent: Praise
created_at: '2022-03-01T01:39:31.662456'
last_modified_at: '2022-03-01T01:39:31.662459'
statistics:
  total_words: 11109
  total_non_words: 1187
quality:
  non_words_ratio: 0.11
